docs/extensions.rst

This sentence seems like a leftover from when i18n was the only extension available, eh?

trim obsolete sentence re: i18n extension

---

jinja2/filters.py

Examples contrary to behavior and description of killwords argument.

Fix incorrect truncate filter docs

---

docs/tricks.rst

Just a typo I found while reading the docs

fix typo "makes sense to defined" -> define

---

jinja2/utils.py

Related pull of pyramid_jinja2: https://github.com/Pylons/pyramid_jinja2/pull/94

Windows returns EINVAL on bogus filenames

---

docs/switching.rst

Clearing up a few bits I found difficult to parse whilst reading the docs on comparing with Django templates.

Switching docs tweaks

---

jinja2/debug.py

Fixes [issue 449](https://github.com/mitsuhiko/jinja2/issues/449)

fix the fancy tracebacks on Python 3

---

jinja2/filters.py

Fix typo: "the iterates" > "that iterates"

---

jinja2/sandbox.py

These are worth fixing since they appear in the docs here: http://jinja.pocoo.org/docs/dev/sandbox/

Fixed a few spelling mistakes in a docstring

---

docs/faq.rst

Update the Google App Engine example code to be compatible with the latest google app engine devserver.

Update GAE example code

---

README.rst

Suggest installing via Pip

---

README.rst

* Add syntax highlighting
* Fix build table which doesn't display on Github RST renderer

README - fixes

---

jinja2/utils.py

Replaced 'messuring' with 'measuring'

Fixed typo in jinja2/utils.py

---

jinja2/utils.py
tests/test_api.py

Fixes #493
Fixes #474
Fixes #524

Give Cycler a next() method so that it works in python2 and 3

---

setup.py

I just don't know if the correct version is 2.9.7.dev or 2.10.dev

Fixed incorrect merge in setup.py

---

ext/Vim/jinja.vim

disable recursive comments in vim syntax file

---

jinja2/nodes.py

Inline template tests during optimization

---

CHANGES.rst
docs/api.rst
jinja2/compiler.py
jinja2/ext.py
scripts/pylintrc
setup.py

Trivial typos

---

docs/intro.rst

There is now Python 3 support...

Remove old statement about Python 3

---

CHANGES.rst
docs/templates.rst
jinja2/__init__.py
jinja2/asyncsupport.py
jinja2/environment.py

Lazy asyncsupport.patch_all()

---

docs/templates.rst
tests/test_lexnparse.py

Extra  description and tests for the correct behavior of  {% raw %}

{% raw %} tests and note for documentation

---

docs/templates.rst

remove html+jinja highlight

---

docs/templates.rst

Might need a little padding tweak to the CSS for spacing under the table.  References issue #584

Quick lookup table for builtin filters and tests-- references #584

---

jinja2/filters.py

Clarify in docs that last filter doesn't work with generators

---

tests/test_imports.py

Two removed lines are identical to the previous ones. Looks like occasional copy-paste issue.

Remove duplicated testcase

---

docs/api.rst
docs/templates.rst

Document nested extends and super.super

---

docs/templates.rst

Remind not to put block in if statements in doc

---

CHANGES.rst
jinja2/sandbox.py
tests/test_api.py

Fixes https://github.com/pallets/jinja/issues/933

Fix memory usage bug in Python 2 by using correct version of range

---

jinja2/filters.py

Tweak docs grouper chapter

---

jinja2/filters.py

document that sort is stable

---

MANIFEST.in

Fix MANIFEST.in to include renamed license file

---

tests/test_api.py
tests/test_security.py

This PR just includes the simplest cases to make review simple as this is my first PR to the jinja project.

Eliminate dead code by using pytests.raises instead of try/except/else

---

docs/templates.rst
jinja2/filters.py
jinja2/nodes.py

closes #273
closes #423
closes #547
closes #566
closes #762
closes #1068

Address various documentation requests

---

docs/extensions.rst
docs/templates.rst
jinja2/ext.py

- explain enabling newstyle
- organize newstyle advantages
- mention escaping percent signs for formatting
- mention marking format parameters as safe
- fix newstyle ref
closes #421
closes #516
closes #896

clean up i18n documentation

---

CHANGES.rst
jinja2/environment.py

compile writes utf8

---

CHANGES.rst
src/jinja2/compiler.py
tests/test_async.py

Fix attribute access in async code.

---

CHANGES.rst
src/jinja2/loaders.py
tests/test_loader.py

Use importlib machinery to fix PEP 451 import hooks

---

src/jinja2/loaders.py

Simple typo fits on the example doc

Update oudated CutomLoader code example

---

.dependabot/config.yml

try to make dependabot ignore editable line

---

docs/api.rst
src/jinja2/loaders.py

update package and filesystem loader docs

---

.github/workflows/tests.yaml
.gitignore
setup.cfg
src/jinja2/compiler.py
src/jinja2/environment.py
src/jinja2/ext.py
src/jinja2/filters.py
src/jinja2/nativetypes.py
src/jinja2/nodes.py
src/jinja2/runtime.py
src/jinja2/sandbox.py
tests/test_api.py
tests/test_asyncfilters.py
tests/test_ext.py
tox.ini

Fixes #1246 
* Add missing type hints (these are intended as an initial set of type hints, to be added upon and improved later)
* Setup MyPy to run as a Github Action

Setup mypy

---

docs/templates.rst

- fixes #<issue number>
Checklist:

Update templates.rst to fix small typo

---

CHANGES.rst
docs/templates.rst

Some docs cleanup I had stashed for #1233 but forgot to push before it was merged.

update docs about required blocks

---

docs/extensions.rst

update docs on adding extensions post-creation

---

CONTRIBUTING.rst

Include instructions for installing docs prerequisites

---

CHANGES.rst
docs/extensions.rst
src/jinja2/ext.py
tests/test_ext.py

add pgettext to InternationalizationExtension

---

CHANGES.rst
src/jinja2/nativetypes.py
tests/test_async.py

Add async support to NativeEnvironment

---

docs/templates.rst
src/jinja2/filters.py

Update wording on dictionary default ordering

---

src/jinja2/filters.py

Fix map documentation

---

docs/templates.rst

Looks like this has been sitting there since the dawn of jinja :o

Fix incorrect docs - line statements have no default

---

CHANGES.rst
src/jinja2/asyncfilters.py
src/jinja2/filters.py
tests/test_filters.py

Ability to set default value in groupby filter

---

src/jinja2/compiler.py

Initial refactor for async statements in compiler.py cc @davidism

Identify an async environment, and return the corresponding strings

---

src/jinja2/filters.py
src/jinja2/lexer.py
src/jinja2/loaders.py
src/jinja2/nodes.py
src/jinja2/utils.py

use exception chaining

---

docs/templates.rst

remove reference to macro.defaults

---

CHANGES.rst
src/jinja2/compiler.py
src/jinja2/environment.py
src/jinja2/nativetypes.py
src/jinja2/runtime.py
tests/test_nativetypes.py

Support native types in macros

---

src/jinja2/filters.py

Fix a little typo in `do_sort` docstring.

Fix little typo in docstring

---

docs/sandbox.rst

Based on emailed feedback, add more discussion of additional security on top of the sandbox. Also rewrite the introduction and operator sections.

rewrite sandbox docs, add more security discussion

---

docs/templates.rst

fix get_template example

---

src/jinja2/loaders.py

This pull request fixes #1697.

Replacing os.path.sep with os.sep in loader

---

.github/workflows/tests.yaml
tox.ini

test 3.11 final
test 3.12 dev
update for tox 4

update tested python versions

---

src/jinja2/loaders.py
tests/test_loader.py

fix test_package_zip_list on 3.13

---

docs/extensions.rst

Refs the discussion at https://stackoverflow.com/a/78970088 to make it clearer what to do to hook up `i18n`.

Improve documentation for initializing the i18n extension

---

src/jinja2/filters.py

fix list comprehension example

---

src/jinja2/loaders.py

The `ModuleLoader` example seems copy pasted from `ChoiceLoader`. As a result it's not immediately clear how their API differ.
Checklist:

Simplify example for ModuleLoader

---

docs/nativetypes.rst

document SandboxedNativeEnvironment pattern
