jinja2/__init__.py
setup.py

This fixes the problem of python packaging considering an installed dev version older than 0.0.

Use PEP440-compatible dev version

---

CHANGES
jinja2/_compat.py
jinja2/tests.py
jinja2/testsuite/tests.py

While making Jinja Python3-compatible, the check for long was removed instead of being replaced with version-specific `integer_types`.
Also added testcases for `float` and `complex` numbers.

Fix `long_integer is number` check in Python 2

---

CHANGES
jinja2/parser.py
jinja2/testsuite/core_tags.py

Python rejects such function definitions because it doesn't make much
sense to have arguments with no default values after arguments with
default values.
Jinja did allow them, but handled them improperly (associating the
default value with the wrong argument).
Due to how broken the current behavior is, it makes more sense to reject
templates containing such defintions instead of trying to handle them
properly. Both cases are going to break existing code containing such
definitions, but besides the fact that possibly no such code exists it
is better to fail with a clear error than to silently change the values
of arguments.
This fixes #364

Disallow f(x, y=1, z) and similar nonsense

---

tox.ini

E.g.: `tox -e py26 -- -v jinja2.testsuite.core_tags`

tox.ini: Use {posargs} so that test runner arguments can be passed to tox

---

jinja2/filters.py

The public documentation of the filters contained the typo "appying".

fix copy-pasted typo in filter docstrings

---

docs/templates.rst

Fixed html tags in base template example. Since I was removing the
xmlns="http://www.w3.org/1999/xhtml" tag, it seemed like a good time to
update the examples to the html5 doctype.
(in response to issue: https://github.com/mitsuhiko/jinja2/issues/394)

Updated template documentation examples

---

jinja2/defaults.py

lambda **kw: kw is not equivalent to the dict constructor. It is much less useful.
In particular it doesn't accept a sequence of pairs.
Why not put dict itself into the DEFAULT_NAMESPACE?
Principle of least surprise, etc.

Replace lambda for 'dict' in with dict itself

---

jinja2/filters.py

`foo["bar"]` is an item lookup, so saying that items are not looked
up with that as an example is confusing.

Change attr filter example to match description

---

docs/api.rst

The example nl2br custom filter inserts escaped `&lt;br&gt;` <br> tags as the `Markup.replace` method seems to pass `str`/`unicode` arguments through `escape`.

Custom Filters example inserts escaped <br>s

---

jinja2/filters.py

Fixed typos on docstrings of template filters.

---

docs/contents.rst.inc

Duplication of index and search links on main page of documentation.

---

docs/cache_extension.py

No longer working with current code base since the TokenStream.next() method was removed.

FIX DOC-EXAMPLE: cache_extension.py

---

ext/Vim/jinja.vim

Given a statement like `{% set sep = '\\' %}`, the syntax highlighter was considering the literal `'\\'` to be a literal quote inside the string by matching `\'` and thus highlighting the rest of the entire document as a string.
This change fixes that issue by adding some regex to ensure that an escaped quote is preceded by an uneven number of slashes (that is, `'\\\\\''` would accept the literal string `\\'` without issues). A`"` quoted string is modified the same way.

Fix literal \ characters at the end of a string

---

jinja2/_compat.py

With mitsuhiko/flask#1539 the `with_metaclass` function got impoved in Flask, see the comments there. So we should use the same implementation in jinja2 as well. Note that this PR merely copied over the code from Flask.

Improve with_metaclass()

---

docs/switching.rst

* http://jinja.pocoo.org/docs/dev/switching/#conditions has been completely inaccurate since the Django 1.4 release, which was over 2 years ago. Reference: https://docs.djangoproject.com/en/1.4/ref/templates/builtins/#if
* Modern Django (1.8) has full support for `if`, `elif`, and `else` statements: https://docs.djangoproject.com/en/1.8/ref/templates/builtins/#if
Just noticed this discrepancy again while integrating Jinja2 into djangopackages.com. :smile:

Remove conditions segment of Django section

---

.travis.yml
tox.ini

Python 3.5 is out. So we should run tests there as well.
Note that Travis currently requires to specify `3.5.0` explicitly.

Added Python 3.5 to tox and Travis configuration

---

.travis.yml

Travis CI supports PyPy as well. So we should run the tests there as well.
Note that there is also `pypy3`. However, PyPy 3 is currently based on Python 3.2 which isn't supported.

Added pypy to the list of Python versions tested by Travis CI

---

jinja2/utils.py
tests/test_utils.py

Escape target attribute in the urlize function in utils.py.

---

docs/extensions.rst
docs/integration.rst

The header at https://babel.edgewall.org/ says
> **The Babel project has moved!**
> After this project has sadly been stalled for a long time, Armin Ronacher (@mitsuhiko) of Flask fame has kindly volunteered to get the project back up to speed. For a variety of reasons this means Babel is leaving the Edgewall.org umbrella.
> 
> The new home of the project is at babel.pocoo.org, the code is now hosted on Github at github.com/mitsuhiko/babel. In the coming days, we will make the Babel Trac environment on edgewall.org readonly

Change links for Babel to new docs location.

---

.travis.yml

This should result in faster Travis builds and also gets rid of the warning currently shown on builds.

Use container-based travis infrastructure

---

setup.py

It seems that somebody forgot to keep the compatible Python versions listed in `setup.py` up to date. Python 3.5 is already out, and the tests are already performed and pass there. However, in `setup.py`, Python 3.3 is the latest version listed.

Added Python 3.4 and 3.5 to the classifiers in setup.py

---

jinja2/_compat.py
jinja2/environment.py

Since jinja2 doesn't support any version older than Python 2.6 anymore, we can simply use the `next` built-in function rather than abstracting `it.__next__` (Python 3) and `it.next` (Python 2) ourselves.

Use partial(next, ...) instead get_next()

---

jinja2/filters.py

I realized that the `groupby` filter applies sorting on the grouped result. This however is unnecessary, since we already sort the input using the same expression we group by and `itertools.groupby` doesn't change the order (which is the reason you have to manually sort the input for in the first place).
So sorting the the result again doesn't have any effect, beside hurting performance and increasing memory usage, since it will effectively sort for the expression it has been sorted by before, as it's computed value is stored in the first item of the tuples in the sequence.
Note that I also had to replace `map` with a list comprehension to make sure that we still return a list in Python 3, where `map` returns a lazy-evaluated iterable. And since `_GroupTuple` doesn't have to take a single …

Got rid of redundant sorting in groupby filter

---

docs/intro.rst
jinja2/environment.py

- fixes #543 (removing `sudo` from installation instructions)
- fixes #544 (using `True` instead of true)

Small documentation fixes

---

jinja2/environment.py
tests/test_loader.py

In 6671b973e6de5abc46829a27fd3bbb989d68ca3a the load_template method
was altered to use a cache key other than the template name. The key
chosen was the abs path as returned from the loader get_source
method. Unless there is no path in which case the name is
used. Unfortunately this introduced a performance regression, #485, as
the get_source method (in the FileStoreLoader) loads the template
(causing IO).
The purpose of #332 was to allow the loader to change whilst ensuring
the correct template was loaded, i.e. to fix this case
env.loader = loader1
env.get_template('index.html') # return loader1/index.html
env.loader = loader2
env.get_template('index.html') # also return loader1/index.html because of cache
This commit changes the cache key to be a combination of a hash of the
loader and …

Change cache key definition in environment

---

jinja2/environment.py
tests/test_loader.py

Changing from a tuple of the loader ID and template name to a weakref
to the loader and the template name should avoid situations whereby
the loader has changed, yet the cached templates are returned. This
would occur if the id of the new loader matches the old. A weakref is
preferred over a direct reference so that the loader can be garbaged
collected.
This change was suggested in #583 by @iceboy-sjtu.

Change environment cache key construction

---

.github/ISSUE_TEMPLATE.rst

#594
Project contributors will automatically see the template's contents in the issue form body. Templates customize and standardize the information you'd like included when contributors open issues.
More info: https://help.github.com/articles/creating-an-issue-template-for-your-repository/

Added a GitHub issue template

---

jinja2/loaders.py

Replaced 'fileame' with 'filename'

Fixed typo in jinja2/loaders.py

---

jinja2/filters.py

This commit replaces the use of terminal inline flags in a regular expression in
`re.compile`,
re.compile(r'\w+(?u)')
with arguments to the `re.compile` function itself,
re.compile(r'\w+', re.UNICODE)
because the former is deprecated as of Python 3.6 (see https://bugs.python.org/issue22493).

Uses re.compile flags argument, not inline flags

---

.travis.yml
CHANGES
Makefile
docs/api.rst
jinja2/__init__.py
jinja2/asyncfilters.py
jinja2/asyncsupport.py
jinja2/compiler.py
jinja2/environment.py
jinja2/filters.py
jinja2/runtime.py
jinja2/utils.py
setup.cfg
tests/conftest.py
tests/test_async.py
tests/test_asyncfilters.py
tests/test_filters.py

This experimental branch adds support for async generators in most places
in Jinja2.  This means that filters now work with async iterators just as
much as the entirety of Jinja2 can now render to an async generator.
More importantly this also means that you can now call things that return
coroutines in templates and Jinja2 will automatically await the call.
The implementation is based on an internal monkeypatch which is not the
nicest in the book but seems to work good enough to make the code
maintainable for different Python versions.
The intro to the feature is here: https://github.com/pallets/jinja/blob/2b03052c9b6f7028e5cb79fb96440a0560bc4340/docs/api.rst#async-support

Add async Support to Jinja 2

---

tests/test_security.py

Previously, two tests where not executed because of name collision

Rename tests to avoid name collision

---

jinja2/runtime.py
tests/test_api.py

Setting **sub** equal to _fail_with_undefined_error so subtractions with undefined variables will fail properly like other arithemtic operations.

Subtraction from Undefined does not raise UndefinedError

---

jinja2/tests.py
tests/test_tests.py

It can be helpful to have a test for values that are greater or less than
another value, especially when looping over lists and using `select()` or
`selectattr()` filters. This patch adds tests that allow a developer to
check if a value is greater or less than another value.
For example, if I have a list of vehicles and I want to find the motorcycles:
vehicles | selectattr('wheels', 'lessthan', 3)
Or, if I want to find large trucks:
vehicles | selectattr('wheels', 'greaterthan', 4)
Tests are included.

Add test for greater/less than

---

CHANGES
jinja2/compiler.py
jinja2/debug.py
jinja2/environment.py
jinja2/idtracking.py
jinja2/meta.py
jinja2/nodes.py
jinja2/runtime.py
tests/test_api.py
tests/test_core_tags.py
tests/test_debug.py
tests/test_ext.py
tests/test_idtracking.py
tests/test_imports.py
tests/test_regression.py

This branch implements correct identifier tracking through aliasing. This basically solves Jinja's oldest bug which is that it tries to trivially map identifiers onto Python scoping which cannot work because Python scoping is not expressive enough to support all of Jinja's features.
This will also fix a ton of other issues and open up heavily improved includes.
The main breakage this causes which is known is that code that overrides Context now needs to override `resolve_or_missing` instead of `resolve` if it wants custom resolve support.

WIP: Correct Identifier Tracking

---

jinja2/filters.py
tests/test_filters.py

Quoting https://twitter.com/dakami/status/778661907179958272:
> All user experiences that use ... after exposing _almost_ an entire message, are failed user experiences. File bugs.  I'm serious.
If [Dan Kaminsky](https://en.wikipedia.org/wiki/Dan_Kaminsky) thinks it's a good idea, it is.
1. Ensure that the requested max length be at least as long as the
requested `end` value (e.g. 3 in the case of '...'). Fixes #539
2. Add `leeway` parameter so that strings that just barely miss the
requested max length cutoff can still be spared from unwanted truncation.
Default value is 5.
3. No longer append a space before appending `end` under any circumstances.
Adding whitespace before ellipsis punctuation in English is grammatically
incorrect.
I've been wanting to fix 2. and 3. for a while. The …

Fix and improve do_truncate

---

jinja2/filters.py

This is the cause of failing tests. Attempt to overload methods on namedtuple with that of builtin tuple with attribute \_\_unicode__ is not needed. tuple and namedtuple do not have a \_\_unicode__ method

fix failing tests: removed some broken code

---

jinja2/tests.py
tests/test_tests.py

This PR introduces an implementation for an `in` test. (edit: The test was originally named `elementof`, see discussion below.)
In conjunction with the `selectattr` filter (or `rejectattr` for negation) this test can be used to extract values from one sequence having attributes that match at least one element of another sequence. It is a thin proxy for Python's `in` operator – like `equalto` is for `==`. While it is trivial to implement this using a custom test by Jinja's users i'd argue that the addition of this test to the Jinja core provides feature parity with existing functionality with respect to `equalto`.
When writing Ansible plays (which uses Jinja2) I hit a wall trying to filter a list of dicts on their name attribute inside of a Jinja2 expression.
When your rendering target is …

Add in test

---

jinja2/filters.py

This is implied but poorly documented. A few examples make it clear.
The first example, "select odd", was already duplicated- I don't know why.

add examples showing > 1 argument in filter

---

tests/test_regression.py

Looks like it was left in from debugging.

Remove print() output during test

---

CHANGES
jinja2/utils.py
tests/test_filters.py

Make tojson always safe (fix #709)

---

AUTHORS
CHANGES
docs/templates.rst
jinja2/asyncsupport.py
jinja2/compiler.py
jinja2/runtime.py
tests/test_async.py
tests/test_core_tags.py

This should solve the problems related to not being able to keep state across loop iterations (e.g. #641) once and for all.

Add previtem/nextitem/changed() to loop context

---

CHANGES
docs/api.rst
docs/templates.rst
jinja2/__init__.py
jinja2/compiler.py
jinja2/defaults.py
jinja2/idtracking.py
jinja2/nodes.py
jinja2/parser.py
jinja2/runtime.py
jinja2/utils.py
tests/test_core_tags.py

This solves more complex cases affected by #641 where #676 is not sufficient.
Somewhat dumb example showing how it works:
```python
{% set ns = namespace(found=false) %}
{% for item in [1, 2, 3] %}
{% set ns.found = item == 3 %}
{% endfor %}
Found: {{ ns.found }}
```

Add namespace objects that support attribute assignment 

---

CHANGES
docs/api.rst
docs/extensions.rst
docs/templates.rst
jinja2/defaults.py
jinja2/ext.py
tests/test_ext.py

Same behavior as in Django: All linebreaks and the whitespace surrounding them are replaced with a single space. Also added a policy `ext.i18n.trimmed` to enable this globally (can be overridden using the `notrimmed` modifier).
closes #504
---
Note: There is one minor case of backwards incompatibility which has no real-world implications. This was already valid Jinja code: `{% trans somevar %}...{% endtrans %}`, making the following ambiguous:
{% trans trimmed %}
hello world
{% endtrans %}
However, `trimmed` is a somewhat unlikely variable name, especially in the context of a `trans` block and the fact that you can specify variables without an assignment there is undocumented. So I don't think anyone is using the combination of these two things. When using a variable assignment the …

Add support for `{% trans trimmed ... %}`

---

CHANGES
jinja2/filters.py
tests/test_filters.py

min and max filters

---

CHANGES
docs/jinjaext.py
jinja2/tests.py
tests/test_tests.py

I added the Python short names for the operators as well as the symbols. I kept the long names for the three existing tests.
`parse_test` is adjusted to allow comparison symbols as test names, so that they can be used in direct tests as well as filters.
```html+jinja
{{ x is <= 5 }} isn't very useful, but it's allowed for consistency
{{ x is le 5 }}
{{ x|select('<=', 5) }}
{{ x|select('le', 5) }}
```
Todo:
closes #664

Allow using comparison operator symbols as tests

---

CHANGES
jinja2/parser.py
tests/test_imports.py

Currently token parsing on "from ... import ..." is rather loose — it sees the following invalid code as perfectly valid:
``` django
{% from "functions" import my_function, %}
{% from "functions" import, %}
{% from "functions" import %}
```
This is caused by the parser ignoring non-name values where there should be names, either as the first value or after commas.
This PR ensures only name values are allowed as the first value and any values after commas in the import section.
Sadly this may be a "semi-breaking" change, as it removes some functionality that should have never existed and hopefully nobody relies on.

Add stricter checking to "from ... import ..."

---

CHANGES
jinja2/parser.py
tests/test_imports.py

Currently we skip an extra comma when "with context" is not provided to the "from" statement. This allows invalid code such as this:
``` django
{% from "functions.html" import my_function,, %}
```
The primary issue with this is that it is not consistent when providing "with context". The following code throws an error, contrary to the previous example:
``` django
{% from "functions.html" import my_function,, with context %}
```
It seems that the comma skipping was originally found in 0611e49 and was accidentally put inside the "with context" check in ea847c5. It was then updated to use "skip_if" in fdf9530.
There doesn't seem to be any reason for this check existing, as commas should never be allowed and serve no purpose in the statement.
Sadly this may be a "semi-breaking" change, as it …

Don't skip an erroneous comma when parsing "from"

---

CHANGES
jinja2/filters.py
tests/test_filters.py

Ignore empty lines in indent filter #681

Ignore empty lines in indent filter #681

---

jinja2/runtime.py

Objects which are backed by native extensions do not provide
a `__call__` attribute, but are none the less callable if the
native extension provides a `tp_call` implementation.
The `jinja2.runtime.Context.call` method unconditionally
access the `__call__` attribute causing an exception to be
raised if the object was a native extension method.
A demo of the problem can be seen using PyGObject:
```
$ cat demo.py
#!/usr/bin/python
from gi.repository import Gio
from jinja2 import Environment
f = Gio.File.new_for_path("/some/file.txt")
print f.get_uri()
t = Environment().from_string("""{{f.get_uri()}}""")
print t.render(f=f)
```
Which when run results in
```
$ ./demo.py
file:///some/file.txt
Traceback (most recent call last):
File "./demo.py", line 10, in <module>
print t.render(f=f)
File …
```

runtime: avoid assumption that all objects provide __call__

---

CHANGES
jinja2/compiler.py
jinja2/idtracking.py
jinja2/nodes.py
jinja2/parser.py
tests/test_core_tags.py
tests/test_idtracking.py

This avoids deep nesting in case of many `{% elif .. %}` blocks (which would fail during execution) and also deep recursion (which may fail during compilation)
fixes #759

Compile `elif` tag to `elif` instead of `else: if`

---

CHANGES
docs/contents.rst.inc
docs/nativetypes.rst
jinja2/nativetypes.py
tests/test_nativetypes.py

This works by having an alternate CodeGenerator that avoids doing to_string
after the yield statement and a new version of concat that handles the returned
generator with a bit more "intelligence".
Related to https://github.com/ansible/ansible/pull/23943
We use jinja heavily in the ansible project. Although it seems to target a text based destination for the renderers, our users have a desire to preserve the types of their templated vars. We also do a lot of internal intercept and post-processing to preserve those types but it's hit or miss and never obvious to the end user what will work and what won't. Therefore, I'm trying to extend jinja beyond what it's original usecase might have been.
This is a first pass and I hope to drive discussion with it and shape it into something the rest …

Add support for the Environment to optionally return native types.

---

CHANGES
docs/templates.rst
jinja2/compiler.py
jinja2/nodes.py
jinja2/parser.py
tests/test_core_tags.py

As suggested in #486, this adds support for filters in `set` blocks:
```
{% set foo | somefilter %}
this is a test
{% endset %}
```

Support filters in set block

---

jinja2/nativetypes.py
tests/test_nativetypes.py

This fixes the issue mentioned in https://github.com/ansible/ansible/pull/32738#issuecomment-358010879:
```
from jinja2 import Environment, BaseLoader
from jinja2.nativetypes import NativeEnvironment
data = "[{{ 'all' }}]"
loader = BaseLoader()
t = Environment(loader=loader).from_string(data)
t_native = NativeEnvironment(loader=loader).from_string(data)
print t.render()
print t_native.render()
```
Before:
```
[all]
[all[all]
```
After:
```
[all]
[all]
```

Allow to pass a list to native_concat

---

jinja2/environment.py
jinja2/filters.py
jinja2/nodes.py
jinja2/sandbox.py
jinja2/utils.py
scripts/pylintrc

Found via `codespell -q 3` using v1.12.0.dev0

Misc. source comment typos

---

jinja2/filters.py

Just a minor documentation bug I noticed while reviewing the documentation for the `min` filter, where it refers to the `attribute` parameter as getting the object with the max value, rather than the min value.

Correct documentation for min filter

---

.gitignore
jinja2/filters.py
tests/test_filters.py

This ~~unescapes after concatenating~~ ensures that we only concatenate `Markup` types to other `Markup` types, to fix a bug introduced in Jinja 2.10 where concatenated lines contain escaped versions of quotes and other characters.
Resolves #823.

Fix escaped characters in indent filter

---

docs/_templates/sidebarintro.html
docs/intro.rst

For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html

Update all pypi.python.org URLs to pypi.org

---

docs/api.rst

i just noticed this upon reading the docs. live long and prosper! and thank you for all your efforts.

Fixes 'awaitable' typo in api.rst

---

tox.ini

pytest-dev/pytest#3771
Pytest 3.7.0 and 3.7.1 had some issues with test collection causing a recursion error. 3.7.2 should fix that, then this can be reverted.

temporarily pin pytest to avoid test bug

---

docs/jinjaext.py
jinja2/_compat.py
jinja2/runtime.py
jinja2/sandbox.py
jinja2/tests.py
jinja2/utils.py

In Python 3.7, importing ABCs directly from the `collections` module shows a
warning (and in Python 3.8 it will stop working) - see
https://github.com/python/cpython/commit/c66f9f8d3909f588c251957d499599a1680e2320
This fixes various DeprecationWarnings such as those:
```
.../jinja2/utils.py:485: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import MutableMapping
.../jinja2/runtime.py:318: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import Mapping
```

Import abstract base classes from collections.abc

---

docs/integration.rst

I spent a while battling to get Jinja syntax highlighting working correctly with Vim, so I made some quick changes to hopefully make it easier for others to get started working with the syntax highlighting.
Notably, I removed the link to the hosted Vim script since it is ten years out of date from the one in this repository, and the original author maintains the script elsewhere (in the GitHub repo I explained at the end section for Pathogen users).
I tested and built this locally before submitting the PR, seen below:

Update integration docs for Vim syntax highlighting

---

setup.py

Tested during CI since 761da6ff612966214fe9e34ac6bc86499e34da26.

Add trove classifier for PyPy support

---

docs/_themes/jinja/static/jinja.css_t
docs/api.rst
docs/intro.rst
ext/django2jinja/django2jinja.py
scripts/pylintrc
tests/test_api.py

Many editors clean up trailing white space on save. By removing it all in one go, it helps keep future diffs cleaner by avoiding spurious white space changes on unrelated lines.

Trim trailing white space throughout the project

---

docs/intro.rst

easy_install is deprecated and its use is discouraged by PyPA:
https://setuptools.readthedocs.io/en/latest/easy_install.html
> Warning: Easy Install is deprecated. Do not use it. Instead use pip.
Follow upstream advice and only recommended supported tools. Replace
with pip.

Remove reference to deprecated easy_install; use pip instead

---

docs/api.rst

This example attempts to handle both Windows-style and Unix-style line endings, but does it wrong; as noted at https://stackoverflow.com/q/12521127/1709587, the regex here will match a single \r\n as if it were a double line-break, which results in all single Windows-style line-breaks getting converted into `<p>` breaks instead of `<br>` breaks as intended.
This patch fixes that by applying Alan Moore's proposed fix from https://stackoverflow.com/a/12521544/1709587 of using a negative lookahead so that a \r cannot be counted as a line break if it is followed by a \n (while still allowing the \r\n combination to count as a line break).

Fix broken nl2br filter example

---

jinja2/asyncfilters.py
tests/test_asyncfilters.py
tests/test_filters.py

While working on the async version of a new applymacro filter, I noticed an underlying issue with map, applying other async filters.  In its iteration, it needed to check whether the return value is a coroutine, and if so wait for it.
The added test, test_map_sum passes when in non-async mode, but without this fix, fails in the async tests.

Fix issue with async's do_map which wasn't awaiting any func's that are coroutines

---

docs/conf.py

These have been broken for about a month now because of the upgrade
to Sphinx 2. This upgrade happened automatically because we do not
have the version pinned.
Luckily this issue appears to only be from having Python 2 syntax in
the docs script, so making that compatible with Python 3 fixes the
error and allows the docs to pass.

Fix tox docs-html builds

---

ext/inlinegettext.py

The 'is' operator is not meant to be used for comparisons. It currently working is an implementation detail of CPython.
CPython 3.8 has added a SyntaxWarning for this.

Fix use of 'is' operator for comparison

---

.travis.yml

The maintenance branch format appeared to change from `[version]-maintenance` to `[version].x` in the recent months, and this broke Travis CI builds made to those branches. Because they no longer meet the branch regex, the pull requests builds against these branches were no longer being run.
This adds the regex for any branch which ends in `.x`, which should catch the new pattern for maintenance branches.

Add new maintenance branch format to Travis

---

.gitignore
CHANGES.rst
docs/api.rst
jinja2/__init__.py
jinja2/filters.py
jinja2/runtime.py
tests/test_api.py

Allows using default values with chains of items or attributes that may
contain undefined values without raising a jinja2.exceptions.UndefinedError.
```python
>>> import jinja2
>>> env = jinja2.Environment(undefined=jinja2.ChainableUndefined)
>>> env.from_string("{{ foo.bar['baz'] | default('val') }}").render()
'val'
```
Fixes #977

Add ChainableUndefined allowing getattr & getitem

---

docs/faq.rst

This just fixes a broken link by deleting it.
I'm assuming Jinja 1 docs. aren't readily available anymore.
I looked for a git tag for version 1 as an alternative target,
but didn't see that either.
(was going to roll other docs. fixes in to make this less trivial, but other docs. fixes are probably more controversial)

fixes #242, deletes link to Jinja 1 docs.

---

jinja2/utils.py
tests/test_utils.py

Added new method itervalues() to LRUCache and deprecated itervalue()
(Fixes pallets/jinja#999)

Added new method itervalues() to LRUCache and deprecated itervalue()

---

docs/api.rst
docs/templates.rst

This commit updates the examples to conform to Python 3 instead
of Python 2, as Python 3 is more acceptable these days.

docs: Python3-ize the examples

---

docs/templates.rst

Fixes https://github.com/pallets/jinja/issues/273
Here is a screenshot of how the page looks:

adds documentation on use of python methods in expressions

---

CHANGES.rst
docs/jinjaext.py
jinja2/_compat.py
jinja2/runtime.py
jinja2/sandbox.py
jinja2/tests.py
jinja2/utils.py

The fix is already in master but probably worth to backport it to the 2.10.x branch (based on this [comment](https://github.com/pallets/jinja/issues/973#issuecomment-503127082)).
Not sure if fixing the warning also makes jinja 2.10.x Python 3.8 compatible, so I only mentioned removing the python 3.7 deprecation warning.

Backport python3.7 collections warning fix

---

jinja2/filters.py
tests/test_filters.py

Added ability to specify multiple attributes in sort:
e.g. foo|sort(attribute='name,id').
This fixes #670

Add ability to specify multiple attributes in sort

---

jinja2/filters.py

without `|list` filter the output is `<generator object do_unique at 0x7f64de96a780>`
So I thought adding it to example was useful.

add list filter to make example match output

---

tox.ini

The pytest plugin was "temporarily" pinned many months back. Given that this is not pinned on the stable branch we should be able to remove it here.
There are likely a few other changes required to get the nightly build working, since it appears as though pytest broke during the release of Python 3.8.0a4.

Unpin Pytest on master branch

---

tests/conftest.py
tox.ini

Clean up the test output with recent versions of `pytest`.

Fix pytest unknown mark warnings

---

CHANGES.rst
jinja2/lexer.py
tests/test_lexnparse.py

Instead of failing with error message "jinja2.exceptions.TemplateSyntaxError: tag name expected", allow the syntax `'{%+'` when `lstrip_blocks == False` with NOP behavior. Fixes #748.

Allow '{%+' to be valid syntax (but NOP) when lstrip_blocks == False. Fixes #748

---

CHANGES.rst
jinja2/filters.py
tests/test_filters.py

added ability to pass default entry to map filter if attribute is not defined. If default is not defined it defaults to an empty string.
fixes #557

add default to map filter

---

ext/Vim/jinja.vim

This is the correct thing to do, vim-wise, although whether
it has any impact depends on how the user has folding set up
in vim. I confirmed that with the change, a folding setup that
uses these variables works, whereas without the change, the same
setup doesn't work.
Change only effects a file that has to be manually copied to the user's
~/.vim/syntax folder, so it won't impact jinja execution in any way.

This is the correct thing to do, vim-wise, although whether

---

CHANGES.rst
jinja2/meta.py
tests/test_api.py

Added a check for global variables when running `find_undeclared_variables`. Tests updated to reflect the change as well.
Written at PyCon 2019 Sprints.
fixes #931

exclude globals from find_undeclared_variables

---

README.rst

Other Pallets projects have a Links section in the README, where I'm adding a link to the official chat. Some of these links duplicate sections above, but it could still be helpful.

Add Links section to README

---

jinja2/exceptions.py

Without this, a TemplateNotFound representation is just `TemplateNotFound()`, which is not really helpfull.
Giving this paramter up permits to have `TemplateNotFound('the template name')` which helps more.

Better repr for TemplateNotFound.

---

CHANGES.rst
jinja2/debug.py

Fix issue #1050: fix a crash in TracebackFrameProxy.set_next() on
Python 3.7 and newer, when Python is build in debug mode.
Since Python 3.7, traceback.tb_next field can be modified: ctypes is
no longer needed.

Fix TracebackFrameProxy.set_next() on Python 3.7

---

setup.py

This will cause the links to show up in the PyPI sidebar, a la click: https://pypi.org/project/click/

Add docs, code and issue tracker links to setup.py

---

CHANGES.rst
jinja2/utils.py
tests/conftest.py
tests/test_api.py
tests/test_utils.py

I was adding tests for Undefined and other utils by running coverage and finding which lines did not have test coverage, then I found there is a deadlock bug in the LRUCache's setdefault method.
As documented in the commit: setdefault was acquiring write_lock, then calling getitem and also
potentially setitem, which both try to acquire the write lock.
Minimal snippet to reproduce the bug with Python 3.7.3 and Jinja 2.10.1:
```python
from jinja2.utils import LRUCache
x = LRUCache(1)
x.setdefault(1)  # <-- deadlock :(
```
It's fixed now and we have better test coverage :smile:

Fix deadlock in LRUCache and improve test coverage

---

CHANGES.rst

2.10.3 is already released on PyPI, so I guess the date in the changelog is a typo.

Fix incorrect release date for 2.10.3

---

jinja2/runtime.py
tests/test_regression.py

Wrapping a `ChainableUndefined` object with Markup causes an `UndefinedError` because Markup thinks that `ChainableUndefined` has an attribute called `__html__` and tries to call it.
This has a couple of knock-on effects; for instance, if you have an environment with `undefined=ChainableUndefined` and `autoescape=True`, you are no longer able to use short conditional expressions, i.e.:
```
def test_short_conditional_with_chainable_undefined_and_autoescape():
env = Environment(undefined=ChainableUndefined, autoescape=True)
t = env.from_string("<{{ 1 if false }}>")
assert t.render() == "<>"
```
This pull request fixes this by defining a method `__html__` that calls `ChainableUndefined.__str__`. We also add a regression test.

Fix bug with when using Markup on ChainableUndefined

---

CHANGES.rst
docs/extensions.rst
docs/templates.rst
jinja2/ext.py
tests/test_ext.py

_Cloned from #798 and rebased with latest `master`._
----
This dumps the available variables, filters and tests. See Issue #174.
This is roughly equivalent to the Django Template Language {% debug %} tag, and typical usage like this:
```
{% debug %}
````
produces output like this:
```python
{'context': {'_': <function _gettext_alias at 0x7f9ceabde488>,
'csrf_token': <SimpleLazyObject: 'lfPE7al...q3bykS4txKfb3'>,
'cycler': <class 'jinja2.utils.Cycler'>,
...
'view': <polls.views_auth.Login object at 0x7f9cea2cbe48>},
'filters': ['abs', 'add', 'addslashes', 'attr', 'batch', 'bootstrap',
'bootstrap_classes', 'bootstrap_horizontal',
'bootstrap_inline', ... 'yesno'],
'tests': ['callable', 'checkbox_field', 'defined', 'divisibleby',
'escaped', 'even', 'iterable', 'lower', 'mapping', …
```

Add support for a {% debug %} extension tag.

---

jinja2/compiler.py
tests/test_lexnparse.py

In response to: [[BUG] Unexpected TypeError when using boolean test inside numeric expression](https://github.com/pallets/jinja/issues/755)
Full details in the latest post in that issue.
Not sure if this is the right place for a unit test, or if this is the right test; I didn't see any compiler-specific tests, and I wasn't able to get them running successfully on my laptop.  However, I applied the change directly to the installed version of jinja2 and it fixed the problem, and the code in the unit test in the commit executes as desired when run on its own.

Fixing compiler handling of parens around boolean comparisons.

---

docs/api.rst
docs/extensions.rst
docs/faq.rst
docs/templates.rst
jinja2/__init__.py
jinja2/asyncsupport.py
jinja2/compiler.py
jinja2/environment.py
jinja2/ext.py
jinja2/filters.py
jinja2/nativetypes.py
jinja2/nodes.py
jinja2/runtime.py
jinja2/sandbox.py
jinja2/utils.py
tests/test_asyncfilters.py
tests/test_filters.py
tests/test_security.py
tests/test_tests.py

closes #1067 
Also cleans up all references to `Markup` and `escape` to point to MarkupSafe instead of Jinja.

explain what autoescaping does

---

tests/test_asyncfilters.py

the two tests were not being run due to having the same name, so changed the names to better reflect the function inputs.

changed test_join functions to unique names

---

CHANGES.rst
jinja2/tests.py
tests/test_tests.py

This PR adds a few more type-related tests.
- **boolean**
Testing if an object is a boolean required 2 tests.
{% if result.value is boolean %}
- **false**
Make this similar to testing none value, not requiring sameas
{% if result.value is false %}
- **true**
Make this similar to testing none value, not requiring sameas
{% if result.value is true %}
- **integer**
The existing 'number' test does not make a distinction between
integer, float or even booleans
{% if result.value is integer %}
- **float**
The existing 'number' test does not make a distinction between
integer, float or even booleans
{% if result.value is float %}
- ~**list**~
~The existing 'sequence' or 'iterable test does not make a distinction
between strings, lists or mappings. Even 'iterable' does not help here.~
{% if …

Add more strict type tests

---

tests/test_api.py
tests/test_async.py
tests/test_imports.py
tests/test_inheritance.py
tests/test_lexnparse.py
tests/test_regression.py

- Replace `try...catch` statements with `pytest.raises`
* This was not done for the one in `test_debug` because it relies on the global exception handler to parse out the traceback

Pytest cleanup

---

.gitignore
CHANGES.rst
jinja2/compiler.py
tests/test_api.py

Finalize only applies to the output of expressions (constant or not). `TemplateData` nodes are static content that should not be finalized.
closes #63 
closes #535 
Given the following template:
```
abc
{{ value }}
def
```
A finalize function that always returned the value "replaced" would result in:
```
replaced
replaced
replaced
```
Now it returns:
```
abc
replaced
def
```
This also cleans up the code gen for the `finalize` function and adds tests for `@contextfunction`, `@evalcontextfunction` and `@environmentfunction`.

don't finalize TemplateData nodes

---

CHANGES.rst
jinja2/utils.py
tests/res/templates2/foo
tests/test_loader.py

When using multiple paths with FileSystemLoader, a template with the same name as a directory will not prevent loading a template in the directory.
closes #821
closes #822
closes #963

skip template with same name as directory

---

CHANGES.rst
docs/templates.rst
jinja2/compiler.py
jinja2/environment.py
jinja2/runtime.py
tests/test_api.py

Use separate undefined object for else-less conditional expressions

---

CHANGES.rst
jinja2/runtime.py
tests/test_runtime.py

- The approach to set length param is costly and should be avoided. only if someone expects the iterator length should the cost be borne.
- Added test cases to validate rendering and LoopContext behavior
fixes #459
fixes #751
fixes #794

Fix for Loop properties revindex and revindex0 still wrong in Jinja2 2.10 #794

---

docs/templates.rst
jinja2/utils.py

closes #1016
Makes it clearer that `next()`returns the current item before advancing, and cleans up the docs in general. Docs are synched with the class docs, but because we want to show the name `cycler` rather than `jinja2.utils.Cycler`, they still have to be written manually.

clarify cycler.next() behavior

---

CHANGES.rst
jinja2/nativetypes.py
tests/test_nativetypes.py

closes #1020 
Due to the way the lexer works, `'{{ a }}', '{{ b }}'` would get parsed as the nodes `'`, `{{ a }}`, `', '`, `{{ b }}`, `'`. `native_concat` would get called on the intermediate node `', '`, which parses to a string, which drops the quotes.
Now, if `literal_eval` results in a string, it is re-quoted except for the top-level concat in `Template.render`. The original quote character is preserved. This carries the quotes through to the final call to `literal_eval`, so quotes around expressions are preserved.
cc @jctanner @mkrizek

preserve quotes between nodes in native env

---

CHANGES.rst
docs/api.rst
docs/extensions.rst
docs/faq.rst
docs/integration.rst
docs/intro.rst
docs/sandbox.rst
docs/switching.rst
docs/templates.rst
docs/tricks.rst
examples/bench.py
examples/rwbench/django/layout.html
examples/rwbench/genshi/layout.html
examples/rwbench/jinja/layout.html
examples/rwbench/mako/layout.html
examples/rwbench/rwbench.py
ext/Vim/jinja.vim
ext/django2jinja/django2jinja.py
ext/djangojinja2.py
ext/inlinegettext.py
jinja2/__init__.py
jinja2/bccache.py
jinja2/environment.py
jinja2/ext.py
jinja2/filters.py
jinja2/nodes.py
jinja2/parser.py
jinja2/tests.py
jinja2/utils.py
scripts/jinja2-debug.py

related to #752 
No code changes. Omits the "2" if it's not distinguishing the version from "1".

use "Jinja" instead of "Jinja2"

---

CHANGES.rst
jinja2/utils.py
tests/test_utils.py

continues #844 
closes #843 
`LRUCache.copy()` wasn't calling `_postinit`, so the queue methods pointed at the empty initial queue rather than the copied queue. Previous PR fixed this by calling `_postinit` in `copy`. I've modified this to use `queue.extend` instead of creating an extra queue, so `_postinit` isn't required.

LRUCache.copy's queue methods point to the correct queue

---

examples/basic/cycle.py
examples/basic/debugger.py
examples/basic/inheritance.py
examples/basic/test.py
examples/basic/test_filter_and_linestatements.py
examples/basic/test_loop_filter.py
examples/basic/translate.py
examples/profile.py
examples/rwbench/rwbench.py
ext/django2jinja/django2jinja.py
ext/djangojinja2.py
scripts/jinja2-debug.py

Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.

Use print() function in both Python2 and Python 3

---

CHANGES.rst
jinja2/environment.py
jinja2/nativetypes.py
tests/test_nativetypes.py

closes #1091 
`get_spontaneous_environment` is not a publicly documented API and is only used within `Template.__new__`. It now takes the environment class to create as the first argument.

creating a NativeTemplate creates a NativeEnvironment

---

jinja2/environment.py
tests/test_debug.py

When I have a template with the following contents:
```
Hello World
```
and execute `Template.get_corresponding_lineno()` on it Jinja produces the exception below:
```
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/senko/coverage-jinja-plugin/tests/test_simple.py", line 51, in test_one_line
text, line_data = self.do_jinja_coverage('hello.html')
File "/home/senko/coverage-jinja-plugin/tests/test_simple.py", line 40, in do_jinja_coverage
text = self._render(template, context)
File "/home/senko/coverage-jinja-plugin/tests/test_simple.py", line 18, in _render
template = env.get_template(template_filename)
File "/home/senko/.virtualenvs/Jinja2Coverage/lib/python3.5/site-packages/jinja2/environment.py", line 849, in …
```

handle template.get_corresponding_lineno() for lines without debug info

---

CHANGES.rst
jinja2/filters.py
tests/test_filters.py

`textwrap.wrap()` from stdlib has unexpected behaviour where when
wrapping multiple paragraphs it will not consider existing newlines.
I.e. when your first paragraph ends on col 75, the next paragraph
will be wrapped on col 5 already.
This patch is wrapping each line individually and combining it back
together.
Fixes #175.

Let wordwrap filter respect existing newlines

---

CHANGES.rst
jinja2/filters.py

Small patch that exposes Textwrapper's `break_on_hypens` option to wordwrap filter.
Fixes: #550 
Thank you, regards

Exposing Textwrapper break_on_hyphens option to wordwrap filter

---

jinja2/filters.py
jinja2/utils.py
tests/test_filters.py

Rewrite `filters.do_urlencode` and `utils.unicode_urlencode` docs to be clear about what types are accepted and how they are quoted. Rewrite filter test to use `parametrize`. Apply query string quoting consistently to the key and value, matching browser behavior.

clarify quoting behavior of urlencode filter

---

CHANGES.rst
jinja2/asyncsupport.py
jinja2/compiler.py
jinja2/runtime.py
tests/test_async.py
tests/test_runtime.py

fixes #555 
Previously, `LoopContext` prefetched the next item in the iterable, the internal iterator was advanced one further than the index. This caused issues with `groupby` or other iterators where items depend on the state of the iterator.
Now, the iterator will only advance early for the `length`, `revindex`, `last` and `nextitem` properties, using any other properties in the loop will not mess up `groupby`.
Unfortunately, this couldn't carry over to `AsyncLoopContext` directly. To look ahead in async, you need to `await it.__anext__()` rather than `next(it)`. To `await`, you need to be in `async def`, but only `__anext__` is async, not the properties, and we're not prefetching during iteration anymore. So this reimplements some properties to be async. This has the extra effect of …

don't prefetch next item in loop context

---

CHANGES.rst
jinja2/nodes.py
jinja2/runtime.py

When jinja2 is used from Cython-compiled code, Functions and Methods are not  `types.FunctionType` or `types.MethodType` anymore. Instead they are `cython_function_or_method`. The framework does not recognize decorated functions/methods and doesn't inject the needed parameters before the call execution.
Using `callable` is backward compatible with existing implementation and also compatible with Cython-compiled code.

Use 'callable' instead of typechecking for runtime calls ctx/env injection

---

jinja2/compiler.py
jinja2/nativetypes.py
jinja2/runtime.py
tests/test_api.py
tests/test_async.py

This originally started after I realized that since `NativeCodeGenerator.visist_Output()` is mostly a copy of the code from `compiler.py`, the changes made in #1080 weren't applied to it. To mitigate that in the future, I extracted the differences between them into some internal methods, so `NativeCodeGenerator` only needs to override those instead of the entire `visit_Output` method.
This made me realize that we were doing the same processing to generate the `finalize()` function for every output node, even though it's the same for all of them. Now the compile time function and runtime source are generated once and cached.
Finally, `visit_Output` had two code paths for rendering the source: if there were < 3 nodes, each node would be yielded directly, otherwise a format string was …

refactor visit_Output

---

CHANGES.rst
jinja2/asyncsupport.py
jinja2/debug.py
jinja2/environment.py
jinja2/nativetypes.py
tests/test_debug.py

This greatly simplifies the `jinja.debug` code.
On Python >= 3.7, `tb_next` is directly assignable. On PyPy, use [transparent proxies](https://doc.pypy.org/en/latest/objspace-proxies.html) only if support is enabled. For cpython < 3.7, use ctypes to set `tb_next`. Rewrite the ctypes code to use `py_object` and `pythonapi.Py_IncRef`, which seems to avoid crashing on debug builds. Fixes #1104 
On Python 3, a rewritten `TemplateSyntaxError` would retain the frames from the compiler functions for some reason. Clear these so the template source is the last thing in the traceback. Fixes #763

rewrite traceback rewriting support

---

CHANGES.rst
jinja2/compiler.py
jinja2/nodes.py
tests/test_ext.py

This allows extensions to access locals in the scope from which they were called. Fixes #860

Add a DerivedContextReference node type

---

CHANGES.rst
jinja2/optimizer.py

fixes #733 
Rather than assigning each node visitor manually, `generic_visit` checks if the node is any `Expr` and tries to optimize it, so `Optimizer` doesn't have to be kept in sync with `CodeGenerator`. There were some other nodes (`Pair` and `Keyword`) that had `as_const` but broke other things if they were folded, so this is limited to `Expr`, which seems to be the original intent anyway.

apply optimizer to all Expr nodes

---

CHANGES.rst
jinja2/debug.py
tests/test_debug.py

fixes #457 
Rendering the included template caught, processed, and re-raised the `TemplateSyntaxError`, which was then caught and processed again in the top-level render call. Now prevent such tracebacks from being faked a second time.
This also fixes an issue introduced by #1110 that omitted the other template frames and only showed the template with the syntax error.

TemplateSyntaxError from included template has source

---

CHANGES.rst
jinja2/loaders.py

fixes #1097 
Adds limited support for PEP 420 namespace packages. The template directory is assumed to be provided to by the first contributor encountered in the namespace package's path, and Zip files are not supported.
The loader now tries to import the package, so users will get an `ImportError` if it's misconfigured.

PackageLoader understands namespace packages

---

CHANGES.rst
jinja2/environment.py
jinja2/exceptions.py
jinja2/runtime.py
tests/test_api.py

fixes #1037 
The value passed to `extends`, `import`, or `include` could be a variable, which could be undefined. Some loaders would incidentally trigger the `UndefinedError`, while others such as `DictLoader` would not, producing an unhelpful `TemplateNotFound` message.
Passing `Undefined` to `get_template` raises an `UndefinedError`. If `select_template` raises `TemplatesNotFound`, any undefined values in the list of attempts show as their undefined message rather than the empty string. `get_or_select_template` passes `Undefined` to `get_template`.

handle Undefined in get/select_template

---

CHANGES.rst
jinja2/exceptions.py
tests/test_debug.py

Implement [`__reduce__`](https://docs.python.org/2/library/pickle.html#object.__reduce__) to fix pickling of TemplateSyntaxError
New test output without the fix (Python 3.8):
```
________________________________________ TestDebug.test_pickleable_syntax_error _________________________________________
self = <test_debug.TestDebug object at 0x109740490>, fs_env = <jinja2.environment.Environment object at 0x1097400a0>
def test_pickleable_syntax_error(self, fs_env):
exc = TemplateSyntaxError('wtf', 42)
pickled_exc = pickle.dumps(exc)
>       unpickled_exc = pickle.loads(pickled_exc)
E       TypeError: __init__() missing 1 required positional argument: 'lineno'
test_debug.py:78: TypeError
```

Fix TemplateSyntaxError pickling

---

CHANGES.rst
src/jinja2/asyncfilters.py
src/jinja2/compiler.py
src/jinja2/environment.py
src/jinja2/nodes.py
src/jinja2/runtime.py
tests/test_runtime.py

Explicit checks for "is True" prevents unexpected behaviour with objects
that are callable and have permissive gettatr(), such as Mock.
Fixes #1145

Use stricter getattr() checks for decorator functions

---

CHANGES.rst
src/jinja2/filters.py
tests/test_filters.py

Currently the `wordcount` filter doesn't properly fail when passed an undefined variable.
This PR updates `do_wordcount` to utilize `soft_str` so that the `StrictUndefined` methods are invoked.
Before:
```pycon
>>> from jinja2 import Environment, StrictUndefined
>>> e = Environment(undefined=StrictUndefined)
>>> t = e.from_string('{{ undef | wordcount }}')
>>> t.render()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/matt/venvs/ansibledev/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/Users/matt/venvs/ansibledev/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File …
```

Use soft_str in do_wordcount, to trigger undefined

---

docs/api.rst

For those who were actually looking for the template design documentation putting a link directly to it might prevent them to have to google for it. When on the API page, there is no direct way to find the template design documentation. Hope this can help others.

Add link to template designer documentation

---

CHANGES.rst
src/jinja2/debug.py

The old way was causing an infinite loop on Python 3.6 32-bit because `PyObject_HEAD` is only 8 bytes on that version, not 32 or 16. Uses a more general way to calculate the size. This was not an issue on Python 3.7+ or PyPy, which don't need `ctypes` to set `tb_next`.
fixes #1162

better PyObject_HEAD size calculation

---

CHANGES.rst
src/jinja2/utils.py
tests/test_api.py

fixes #1177 
Use `type(obj)` instead of `obj.__class__` when formatting undefined message. Django's `LazyObject` defines `__class__` as a property that resolves the lazy wrapper, and if that wrapper raises an `AttributeError` it causes other issues. This is really an issue with the lazy wrapper raising an error, but in this case it can be addressed in Jinja too.

AttributeError in undefined message doesn't cause RuntimeError

---

CHANGES.rst
src/jinja2/lexer.py
tests/test_lexnparse.py

The current version seems to assign wrong line numbers to tokens when whitespace trimming is used. For example this code:
```python
from jinja2 import Environment
if __name__ == '__main__':
env = Environment()
tmpl = env.from_string(
"""\
<html>
<body>
{%- block content -%}
<hr>
{{ item }}
{% endblock %}
</body>
</html>"""
)
print(tmpl.debug_info)
```
prints `[(2, 12), (4, 23)]` when it should be `[(3, 12), (5, 23)]`. In particular, this causes troubles for debuggers (see [here](https://youtrack.jetbrains.com/issue/PY-40968)).
The suggested patch attempts to fix the line number calculation. Please let me know if I have missed something. Thanks in advance!

Fix tokens line number calculation when whitespace stripping is used

---

CHANGES.rst
src/jinja2/utils.py
tests/test_async.py

This fixes https://github.com/pallets/jinja/issues/1180, by allowing `Namespace` instances to undergo the type checks necessary for async compatibility.

Allow namespaces to be used in asynchronously rendered templates.

---

ext/Vim/jinja.vim

I'm not 100% sure that one should not use `setlocal` in a syntax file, but this breaks other filetypes that may include this syntax file, like the vim-markdown plugin if `jinja` is included in its `g:markdown_fenced_languages`.  The `comments` and `commentstring` end up set in the markdown buffer with the jinja settings.
See https://github.com/dhruvasagar/vim-table-mode/issues/162#issuecomment-595317626 for an example of side effects.

Don't use setlocal in syntax file

---

CHANGES.rst
src/jinja2/lexer.py
tests/test_lexnparse.py

Introduced in #858. Closes #1138

Fix unintended lstrip_blocks behavior

---

CHANGES.rst
src/jinja2/nativetypes.py
tests/test_nativetypes.py

If each intermediate group was converted, it could change the final value. The example given in the test is that the string `0.000` evaluates to a float, then renders as `0.0` when combined later, so `0.000{{ 7 }}` would result in `0.07`. Instead, intermediate groups are joined as strings, and only the final result is passed to `native_concat`. This also removes the need for `preserve_quotes` from #1086.
submitted by @mkrizek, closes #1186

native only evals at end of render

---

src/jinja2/filters.py

When iterating over a dict you usually want to pull out the keys and values.

do_dictsort: update example ready to copy/paste

---

docs/api.rst

api.rst: bugfix in docs, import PackageLoader

---

.dependabot/config.yml
requirements/dev.in
requirements/dev.txt

Unfortunately, pinning Sphinx with pip-compile causes Jinja to be pinned as well, which then overwrites the editable install unless it's done afterwards. And adding `-e` in the requirements file causes Dependabot to fail. It doesn't seem like that's going to be solved by pip (pypa/pip#8307), pip-compile (jazzband/pip-tools#1150), or Dependabot (dependabot/feedback#936) any time soon, so for now I'm just going to remove the docs requirements from the dev requirements.
Alternatively could have left them in and required doing `pip install -e .` after `pip install -r requirements/dev.txt`, but I figured just removing it would be less error prone. If users need to build the docs locally, they can do `pip install -r requirements/doc.in` to get the direct dependencies without the sub-dependency …

remove docs requirements from dev requirments

---

src/jinja2/sandbox.py
tests/test_security.py

Summary:
- Removed `sandbox._MagicFormatMapping` as `string.Formatter` now supports empty braces. 
- Tested with both `SandboxedFormatter` and `SandboxedEscapeFormatter` 
Files affected:
- `sandbox.py`
- `test_security.py`
Resolves #1197

Remove sandbox Python < 3.5 compat

---

CHANGES.rst
src/jinja2/asyncsupport.py
src/jinja2/compiler.py
src/jinja2/environment.py
src/jinja2/runtime.py
tests/test_imports.py

Fixes #688 
- Added parameter to `_get_default_module` to take in the current context and make a new module if template globals are found
- Added `self.globals` to the Context class to differentiate between template variables from render variables.

Fix bug with imported macros and template globals

---

CHANGES.rst
docs/templates.rst
src/jinja2/lexer.py
tests/test_lexnparse.py

Resolves #1036 
**Summary**:
- When `trim_block` is enabled and a block ends with `+%}` or `+#}`, the behavior will be ignored.
- Note: does *not* apply to raw start tags (i.e. `{% raw +%}` will raise an error) because they don't process the inner text
- `+%}` is still allowed when `trim_block` is disabled but exhibits NOP behavior  
- So following the example from the original issue, when `trim_block` is enabled:
```jinja
{% if something %}X{% endif +%}
more things
```
results in
```jinja
X
more things
```
**Tests**:
- Added tests to `test_lexnparse.py`
- Specifically added a class for testing trim called `TestTrimBlocks`
- Tests majority of the same cases as `TrimLstripBlocks`
**Files affected**:
- `lexer.py`
- `test_lexnparse.py`

Allow +%} to ignore trim_blocks

---

CHANGES.rst
src/jinja2/nodes.py
tests/test_asyncfilters.py

Detect custom async filters in as_const
- fixes #1279
Checklist:

Fix custom async filters

---

src/jinja2/debug.py

As part of https://github.com/python/cpython/pull/23113 partly
implementing PEP 626 (see https://bugs.python.org/issue42246), the
co_lnotab member of struct PyCodeObject was replaced by co_linetable,
implementing a new line number table.
This commit therefore adds linetable to the list of attributes that
are copied over into the final CodeType executed by fake_traceback()
to ensure proper line numbers and contents in fake stack traces
generated when running under Python 3.10.
Fixes #1333.

Add 'linetable' to the list of preserved CodeType attributes.

---

docs/templates.rst

The `sourcecode` directive didn't work.

Fix "If" example in documentation

---

CHANGES.rst
src/jinja2/nativetypes.py

If there is only single node and it is not a string, there is no point
in passing it into ``literal_eval``, just return it immediately.
One of the examples where passing a non-string node into
``literal_eval`` would actually cause problems is when the node is
``Undefined``. On Python 3.10 this would cause ``UndefinedError``
instead of just ``Undefined`` being returned.
Fixes #1335

native_concat: pass only strings to literal_eval

---

CHANGES.rst
docs/templates.rst
src/jinja2/compiler.py
src/jinja2/nodes.py
src/jinja2/parser.py
tests/test_idtracking.py
tests/test_inheritance.py

Resolves #1147 
Summary:
- Added required field to blocks
- Block nodes now have 4 fields (`scoped` must come before `required` if used together)
- Must be overridden at some point, although not necessarily by the direct child. `TemplateRuntimeError` raised otherwise.
- Required block itself cannot contain anything other than comments or whitespace. `TemplateSyntaxError` raised otherwise.
- With current implementation, rendering the template containing the required block will also raise a `TemplateRuntimeError`.
Test:
- Added tests to `test_inheritance.py`
- Tested up to three levels, made sure correct errors are raised, tested that scoped still works in conjunction with required
- Patched `test_idtracking.py` to include the new field when instantiating Block nodes
Files affected:
- …

Add required attribute to blocks

---

CHANGES.rst
src/jinja2/ext.py
tests/test_ext.py
tests/test_regression.py

Fixes #1203 
Summary:
WithExtension and AutoEscapeExtension now have a display that warns users that they are deprecated and will be removed in 3.1
The 9 tests that rely/test these extensions were modified to include a ```with deprecation``` clause so that the deprecation warning can be part of the expected behavior

 Deprecate 'autoescape'  and 'with' extensions

---

docs/tricks.rst

"Amount" is used for measurements, "number" is used for counts.

Improve diction (amount -> number)

---

CHANGES.rst
docs/api.rst
src/jinja2/defaults.py
src/jinja2/filters.py
src/jinja2/utils.py
tests/test_filters.py
tests/test_regression.py

Fixes #522
Fixes #827 
Fixes #1172
The 'urlize' function does not as expected both in terms of some missing support. Among a few a few of the behaviors were a lack of support for 5/8 of the original TLDs, emails prefixed with `mailto:` would not be returned as links, and no support for `ftp://`.
This PR does not "fix" the latter point, but does add a `policy` that can be set so that the function will create the links.  This can also be used to add support for any arbitrary URI scheme.
Specifically:
- Adds mailto: link support (issue #1172)
- Adds an `extra_uri_schemes` policy and parameter to address lack of `ftp:` support and allow for other schemes (for example `tel:`) to be added as needed. (issue #522 and PR #587)
- Parentheses at the end of a URL are now included if they match an …

Improve and extend urlize

---

CHANGES.rst
src/jinja2/utils.py

Match leading and trailing punctuation as separate steps. For trailing punctuation, perform a basic check first to reduce backtracking. Update the email regex to reduce backtracking and also be more accurate: the domain part must start with a word character, and the tld only matches word characters.
This is backported from #1195, but only includes the regex speedups, not the other changes.
Checklist:
- ~Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.~
- ~Add or update relevant docs, in the docs folder and in code.~
- ~Add `.. versionchanged::` entries in any relevant code docs.~

backport urlize speedup

---

src/jinja2/filters.py
src/jinja2/utils.py

The docs for the `tojson` filter were copied from Flask's `htmlsafe_dumps`, so they were a bit confusingly worded in context.
Also renamed the `dumper` arg to `dumps` in `htmlsafe_json_dumps`. This function isn't documented as part of the external API.

update tojson docs

---

CHANGES.rst
src/jinja2/filters.py
tests/test_filters.py

According to Issue #1331, the map filter doesn't allow values like [],{},(),None etc ( that automatically default to False ) to be set as the value to the default argument. The user can now set False values to the default argument of the map filter in Jinja2.
- fixes #1331 
Checklist:

Map filter can use False as default

---

CHANGES.rst
src/jinja2/compiler.py
src/jinja2/runtime.py
tests/test_regression.py

Fixes #768  and #1088 (closed as dupe but turned out to be slightly different)
Summary:
- Scoped blocks can now access `loop` and its special variables
- `contextfunction` can access variables set inside of loops and blocks
- Achieved by adding an attribute to `Frame`, tracking assignments made in loops or blocks, and passing it as `extra_kwargs`
Files Changed:
- `compiler.py`
- `runtime.py`
- `test_regression.py`

Fix bugs with contextfunction and loop variables

---

CHANGES.rst
src/jinja2/environment.py
tests/test_regression.py

Fixes #295
Summary:
- Issue affected templates rendered and cached due to `extend` and `include` tags 
-  Now updates Template object with new globals, if any, when retrieving from cache 
Files affected:
- `environment.py`
- `test_regression.py`

Fix bug with cached templates not registering new globals

---

CHANGES.rst
docs/api.rst
src/jinja2/environment.py
tests/test_regression.py

Add detail about the intended use of environment and template globals after the comments in #295. Rewrite the docs for `get_template`, `select_template`, `get_or_select_template`, and `from_string`.
Changes `environment.make_globals` to always return a `collections.ChainMap`, even if no template globals are given. The map prefers a dict of template globals and falls back to the environment globals. Changes will only modify the template dict, not the environment. Globals are still global, but changes to the template will only ever affect the template, while changes to the environment will still be reflected in all templates, even those that provide template globals. This allows `_load_template` to do `template.globals.update()` instead of more complex logic. Continues #1244
fixes #1376

Template globals use ChainMap, more docs about globals

---

CHANGES.rst
src/jinja2/compiler.py
src/jinja2/runtime.py
tests/test_filters.py

Resolves #842 
- Undefined filters nested in if/elif/else statements and conditional expressions will cause an error only if executed during runtime
Files changed:
- `nodes.py`
- `compiler.py`
- `runtime.py`

allow optional use of a filter based on its existence

---

CHANGES.rst
docs/api.rst
src/jinja2/compiler.py
src/jinja2/environment.py
src/jinja2/nodes.py
src/jinja2/tests.py
tests/test_filters.py
tests/test_tests.py

#1248 allowed deferring checking if a filter exists until runtime when writing the filter within in an if block. To make it easy to take advantage of such optionally available filters, this PR adds an `is filter` test.
This required allowing tests to be decorated with `@environmentfilter`. It's not clear why this wasn't allowed before. The docs mentioned it wasn't possible, but didn't give a justification. Perhaps the idea was that tests should be as simple as possible; if so that's up to the discretion of a project now.
Tests are essentially the same as filters now. The difference is only the syntax used to call them and the namespace they're registered in. Most of the code in `nodes`, `compiler`, and `environment` is common between the two, so it was refactored to extract it. Tests …

add 'is filter' and 'is test' tests

---

src/jinja2/asyncfilters.py
src/jinja2/environment.py
src/jinja2/filters.py
src/jinja2/runtime.py
src/jinja2/tests.py
src/jinja2/utils.py

Add type annotations to filter and test functions. #1255 started adding annotations for filters, but had a number of missing or less accurate annotations. I'm not sure how useful this is, but I wanted to be thorough.
- closes #1255

add type annotations to filters and tests

---

CHANGES.rst
src/jinja2/filters.py
tests/test_filters.py

Implemenented also indention with tabulator characters instead of
whitespace characters. This will also allow the use of other characters or character sequences. It's the more generic way I already promised in #1166, choose the best and close the other one.
This is needed if this is used within a template with a specified tab indention. ;-)
Kind regards
Lars

indent filter can indent with arbitrary characters

---

CHANGES.rst
src/jinja2/runtime.py
tests/test_api.py

Fixes #1198. I'm assuming this is the desired behavior -- let me know if not!

Raise UndefinedError from Undefined.__contains__

---

CHANGES.rst
src/jinja2/runtime.py
tests/test_async.py

Allows iterating over `ChainableUndefined` when using `render_async`.
Added `__aiter__` method to `Undefined` which `ChainableUndefined` inherits from.
- fixes #1293
Checklist:

Add __aiter__ to Undefined

---

CHANGES.rst
src/jinja2/lexer.py
tests/test_regression.py

Python `str.splitlines()` splits by [more characters][1], which, however, causes problems when keeping these special characters in processed templates is desirable, i.e. the linked bug reports.
The `keep_trailing_newlines` logic is reworked because `str.splitlines()` removes them already (so they had to be added), while `re.split` doesn't so they have to be removed.
[1]: https://docs.python.org/3/library/stdtypes.html#str.splitlines
- fixes #769
- fixes #952
- fixes #1313
Checklist:

Fix unicode newlines

---

docs/templates.rst

Came across the ~ character in an existing template and it was hard to find the help docs via a web search. Adding tilde and pipe may make the help docs easier to find.

Add symbol names for tilde and pipe

---

docs/api.rst
src/jinja2/__init__.py
src/jinja2/utils.py
tests/test_asyncfilters.py
tests/test_filters.py
tests/test_regression.py
tests/test_security.py
tests/test_tests.py

These were still left over from Jinja's early days. Noticed they were still exported and documented, so now the Jinja versions show deprecation warnings pointing to markupsafe.

Markup and escape should be imported from markupsafe

---

CHANGES.rst
docs/api.rst
src/jinja2/runtime.py
tests/test_regression.py

Changed the metaclass logic to check if the names were defined on the child class instead of comparing the function objects. `_fast_resolve_mode` was never getting triggered, which suggested comparing the objects wasn't completely reliable anyway. Inlined the `resolve_or_missing` function into both methods.
- fixes #1380 
Checklist:

deprecate legacy resolve mode

---

src/jinja2/utils.py

`str` subclass must override `__new__` instead of `__init__`.
- fixes #1400
Checklist:

fix deprecated `Markup` subclass

---

src/jinja2/__init__.py

This just has the deprecated `Markup` fix from #1401.

release version 3.0.0rc2

---

CHANGES.rst
MANIFEST.in
docs/examples/inline_gettext_extension.py
setup.cfg
src/jinja2/async_utils.py
src/jinja2/bccache.py
src/jinja2/compiler.py
src/jinja2/debug.py
src/jinja2/defaults.py
src/jinja2/environment.py
src/jinja2/exceptions.py
src/jinja2/ext.py
src/jinja2/filters.py
src/jinja2/idtracking.py
src/jinja2/lexer.py
src/jinja2/loaders.py
src/jinja2/meta.py
src/jinja2/nativetypes.py
src/jinja2/nodes.py
src/jinja2/optimizer.py
src/jinja2/parser.py
src/jinja2/runtime.py
src/jinja2/sandbox.py
src/jinja2/utils.py
src/jinja2/visitor.py
tests/test_ext.py

Things I noticed while going through the code:
* `Node.fields` and `Node.attributes` could be dataclasses / annotations instead of a tuple of strings. I already added annotations for all the names to each class, so that type checking the parser and compiler was useful. No nodes add extra `attributes`.
* Various objects have a `copy` method which uses `object.__new__` and other "magic" to create a copy. This code seems to be from 2008, when Python's `copy` module might not have been available? In most cases it should be replaceable with a call to `copy.copy()`, except many of the classes also do `__copy__ = copy`.
* Various things in the compiler could be context managers instead of calling before and after functions: `indent`, `enter_frame`, `push_parameter_definitions`, …

add type annotations

---

CHANGES.rst
setup.py

Forgot to do this for 3.0.0, but nothing actually changed since the last MarkupSafe release candidate, so it's not immediately important.

update markupsafe minimum version

---

requirements/dev.txt
requirements/docs.in
requirements/docs.txt
src/jinja2/environment.py

Otherwise docs builds are broken due to sphinx-doc/sphinx#9216
The Any type is needed to avoid this odd sphinx warning:
> jinja2/nativetypes.py:docstring of jinja2.nativetypes.NativeTemplate::more than one target found for cross-reference 'Template': jinja2.Template, jinja2.environment.Template, jinja2.nodes.Template

Install sphinx 4.1-dev from git

---

CHANGES.rst
src/jinja2/ext.py

Now it shows the line that created the environment with the extensions, instead of internal code creating the extensions.
- fixes #1429

fix context for deprecated extensions

---

tests/conftest.py
tests/test_api.py
tests/test_loader.py
tests/test_utils.py

Similar to https://github.com/pallets/flask/pull/4066/files
Checklist:

Use pathlib in some test places

---

CHANGES.rst
docs/api.rst
src/jinja2/environment.py
tests/test_async.py

Python 3.10 shows a deprecation warning when using `asyncio.get_event_loop` while not in an event loop, which is the case when running the sync `render` method for an async template. Use `asyncio.run` instead, which manages running in an event loop.
`generate` is no longer particularly useful when called on an async template, as calling `run` over and over again would create new loops and be inefficient. So it collects the entire render then yields it item by item so that it's still a generator. `generate` already doesn't seem particularly useful, as only very simple templates without blocks or other internal buffers will actually yield one statement at a time.
I think we should deprecate calling `render` and `generate` if the template is async. It's a blocking call in async mode, and it …

use asyncio.run

---

CHANGES.rst
src/jinja2/compiler.py
tests/test_regression.py

fixes #1427 
changes in f524bcce0cf295941fe665cbcb6846e7e9f39df5 caused assignments in nested loops to still be referenced after the end of the iteration. now, all variables assigned in loops will be cleared from the top level so that jinja won't attempt to resolve them outside of the loop.
Checklist:

fix loop scoping bug

---

CHANGES.rst
src/jinja2/compiler.py
src/jinja2/idtracking.py
tests/test_compile.py

Python3 doesn't keep insertion order for set(), so this sorts some
places for deterministic output for compiled template.
- fixes #1452
- fixes #1453
Checklist:

make compile_templates deterministic

---

CHANGES.rst
src/jinja2/runtime.py
tests/test_api.py

- fixes #1448 
Checklist:
- There was no docs added when this was set, so there shouldn't be doc to remove or change.
- No docstring changed

Only StrictUndefined.__contains__ raises error

---

docs/extensions.rst
docs/intro.rst
docs/make.bat

Replace http:// with https:// in external links in docs.
\* This is a recreated PR due to conflict in rebasing in #1487 .
- fixes #1486

replace http with https in docs

---

setup.cfg

From https://github.com/pallets/jinja/pull/1495#issuecomment-923165800, seems that CPython forgot to address some deprecations to the asyncio API internally, and it's now causing issues in user code that doesn't appear to do anything wrong. Added an ignore for the message.

ignore internal asyncio warning

---

CHANGES.rst
src/jinja2/compiler.py
tests/test_async.py
tests/test_imports.py

* Pass context to `_get_default_module_async` to provide template globals to imports.
* Added tests.
* Refactored existing and new import global tests to use existing fixtures.
* Copied `CHANGES.rst` entry from #1241 since it best described the fix.
Relevant issues and PRs:
- One-liner, relies on the fix in PR #1241
- fixes #1494
Checklist:

Template globals not accessible within imported macros

---

CHANGES.rst
src/jinja2/loaders.py
tests/test_loader.py

`PackageLoader` removes the current directory path segment *after* calling `normpath`. This fixes compatibility with loading from the root of zip imports.
- fixes #1467 
Checklist:

omit curdir from PackageLoader root path

---

tests/test_debug.py

Otherwise the failure looks like this:
>       assert (
m is not None
), "Traceback did not match:\n\n{''.join(tb)}\nexpected:\n{expected_tb}"
E       AssertionError: Traceback did not match:
E         
E         {''.join(tb)}
E         expected:
E         {expected_tb}
E       assert None is not None
I have not done the checklist thing, as most of it does not apply to fixing a representation of a failed test.

Tests: Make "Traceback did not match" an actual f-string

---

.github/workflows/tests.yaml
requirements/dev.txt
requirements/tests.txt
tox.ini

I expect 2 tests to fail for 3.11 until #1527 is merged.

test Python 3.11

---

tests/test_debug.py

Fixes https://github.com/pallets/jinja/issues/1526
Before:
File ".../broken.html", line 2, in <module>
{{ fail() }}
File ".../test_debug.py", line 32, in <lambda>
tmpl.render(fail=lambda: 1 / 0)
ZeroDivisionError: division by zero
After:
File ".../broken.html", line 2, in <module>
{{ fail() }}
^^^^^^^^^^^^
File ".../test_debug.py", line 32, in <lambda>
tmpl.render(fail=lambda: 1 / 0)
~~^~~
ZeroDivisionError: division by zero
- fixes #<issue number>
Checklist:

Tests: Adapt expected traceback regexes for Python 3.11.0a1

---

CHANGES.rst
src/jinja2/debug.py

Use `CodeType.replace` to greatly simplify replacing `co_name` on Python 3.8+. Only Python 3.7 needs to use all positional arguments. No longer need to replace `co_filename`, it's already replaced by `compile`. Remove `try/except` block to avoid hiding errors with this code in the future; need to test that modern GAE works with this.
fixes #1334

simplify CodeType rewriting

---

CHANGES.rst
src/jinja2/nativetypes.py
tests/test_nativetypes.py

native: keep same behavior on Python 3.10

---

CHANGES.rst
src/jinja2/async_utils.py

The types of most rendered values tend to be primitives, so we can avoid a costly call to `inspect.isawaitable` for them. This improves performance by at least 15% in my tests.
- fixes #1514
Checklist:

Reduce async overhead due to auto_await

---

CHANGES.rst
src/jinja2/nodes.py
tests/test_nodes.py

This fixes a regression in commit 60293416db69782fd048a7820667afa4ae7c423b that
changed the `__hash__` implementation of Node from the default pointer
hash, to a hash based on the node fields.
Since these fields contain list objects, they are not hashable, making
every call to `Node.__hash__` fail.
This breaks some third-party usage such as in `django-compressor`
(See: https://github.com/django-compressor/django-compressor/issues/1060)
This change reverts the hash method back to using `object.__hash__` as
the hash implementation.
- fixes #1521
Checklist:

Use `object.__hash__` for `Node.__hash__`

---

docs/templates.rst

closes #1388
Rewrite Template Inheritance / Template Objects section. Call out that it is an advanced use case, that it works for extends, include, and import, and show an example of Python code that loads a template and passes it to `render`.

rewrite docs about extending template objects

---

docs/templates.rst

Jinja evaluates chained pow left to right instead of right to left like Python. Document this. closes #1355

document chained pow order

---

CHANGES.rst
src/jinja2/loaders.py
tests/test_loader.py

If the package is actually a single module file, `spec.submodule_search_locations` is `None`. `spec.origin` refers to the imported file, use the parent directory in that case. fixes #1512

PackageLoader works with single module file

---

CHANGES.rst
docs/api.rst
requirements/dev.txt
requirements/docs.txt
src/jinja2/__init__.py
src/jinja2/ext.py
src/jinja2/filters.py
src/jinja2/runtime.py
src/jinja2/utils.py
tests/test_regression.py

* `WithExtension` and `AutoEscapeExtension` are built-in.
* `contextfilter`, `evalcontextfilter`, `environmentfilter`, `contextfunction`, `evalcontextfunction`, and `environmentfunction` have been replaced by `pass_context`, `pass_eval_context`, and `pass_environment`.
* Remove old `unicode_join` runtime function. Very old compiled templates may need to be recompiled.
* `Context` subclasses must override `resolve_or_missing` instead of `resolve`, legacy mode is removed.
* `unicode_urlencode` renamed to `url_quote`.
* Update Pallets-Sphinx-Themes to use new `pass_context`.

remove deprecated code

---

docs/api.rst

Fixes https://github.com/pallets/jinja/issues/1556.
> If only docs were changed, these aren't relevant and can be removed.
Phew. :+1:

Typo in docs (trailing backtick)

---

CHANGES.rst
docs/templates.rst
src/jinja2/ext.py
tests/test_ext.py

A context string can be passed as the first token to a `{% trans %}` block to use `pgettext` and `npgettext`.
```python
{% trans "title" trimmed count=count %}
```
fixes #1430

specify context for translation block

---

docs/tricks.rst

Update legacy doctype in docs/tricks

---

src/jinja2/environment.py

get_template() uses / separators even on Windows

---

CHANGES.rst
src/jinja2/async_utils.py
tests/test_pickle.py

- fixes #1612 
Checklist:
- [n/a] Add or update relevant docs, in the docs folder and in code.
- [n/a] Add `.. versionchanged::` entries in any relevant code docs.

Fix pickleability of filters decorated with @async_variant

---

CHANGES.rst
src/jinja2/compiler.py
tests/test_async.py

The compiler doesn't add parentheses around the `await auto_await(...)` expression when visiting filters and tests. If a subscription is used after the call, the compiler will produce code that tries to subscript the coroutine instead of the awaited result. This adds surrounding parentheses, which matches other similar situations.
fixes #1573

add parens around `auto_await` for filters and calls

---

CHANGES.rst
src/jinja2/filters.py
tests/test_async_filters.py
tests/test_filters.py

This is a quick implementation test to add support for case-insensitive sorting inside the `groupby()` filter, intended to verify the approach.
Changes:
- Add `case_sensitive` parameter to `sync_do_groupby()`.
- Ignore case when sorting in `sync_do_groupby()` if `case_sensitive=False`
Open questions:
1. Is this approach correct?
2. Should async groupby (`async def do_groupby`) also be changed?
3. Should the default value for `case_sensitive` parameter be `False` for backwards compatibility, or `True` to align with the `sort()` filter behavior?
- fixes #1463 
Checklist:

Add case_sensitive parameter to groupby() filter

---

src/jinja2/lexer.py

Less regexes = win.
Whitespace regex could also detect newlines, but since we're only
matching the part from last newline, it's safer (and more readable)
to use it here.
Checklist:

Re-use existing regex for whitespace detection

---

docs/api.rst
docs/faq.rst
docs/integration.rst
docs/switching.rst
docs/templates.rst

* Add sections on Flask and Django to integration page.
* Clean up wording about comparisons to other template languages.
* Move technical discussions about scope, context, and macros out of the FAQ and to more appropriate pages.
* Extensive rewrites to FAQ entries.
* Rewrite section on ``include`` statement. Fixes #1604

rewrite non-technical documentation

---

CHANGES.rst
src/jinja2/loaders.py
tests/test_loader.py

Similar to an issue with Werkzeug and Flask's `send_file` and `safe_join`, `FileSystemLoader` and `PackageLoader` should use `posixpath.join` instead of `os.path.join`, so that on Windows "drive:" and UNC segments cannot break out of the search directory.

use `posixpath.join` when loading template names

---

CHANGES.rst
src/jinja2/loaders.py
tests/test_loader.py

normpath on final template filename

---

CHANGES.rst
src/jinja2/environment.py
src/jinja2/visitor.py

This brings the options in sync with the options of the \_\_init\_\_ method.
_Note: Please let me know if we want to be able to edit the 'enable_async' option also. I added this now
to streamline the overlay method options with the \_\_init\_\_ method, but perhaps there's no use-case for
changing this at runtime?_
fixes #1645 
Checklist:
- [   ] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
_There are no tests for previous individual arguments of the .overlay method, only a general test in 
test_ext.py, so I also didn't add tests specifically for these options. I did test manually to verify the
options are set on the overlay, but unchanged on the original env. If requested, I can integrate these
into a seperate dedicated test for …

Add missing environment options to the Environment.overlay method

---

CHANGES.rst
src/jinja2/bccache.py

Fix race conditions in FileSystemBytecodeCache.  See https://github.com/pallets/jinja/issues/1654 for a detailed description of the race conditions.
- fixes #1654
Checklist:
- [n/a] Add `.. versionchanged::` entries in any relevant code docs.

Fix Race conditions in FileSystemBytecodeCache

---

docs/api.rst

fix a typo coming from a remaining copy/paste from api/#custom-filters to api/#custom-tests.
I was not sure if the decorators worked for custom tests like custom filters described just above, but I tested with a dummy example, it seems to work.
Maybe it would be nice to include an example like above with @pass_eval_context for the custom filters to be consistent.

Fix typo in docs/api/#custom-tests

---

docs/switching.rst

- Add {{ forloop.counter }}. for consistency in Django example
- Add missing space in Jinja example

Add in docs/switching/#loops little improvement for consistency

---

docs/templates.rst

Closes #1732.
This is purely a documentation change.

Show how {% filter %} can take filter arguments

---

CHANGES.rst
src/jinja2/parser.py
tests/test_inheritance.py

An update to flake8-bugbear started showing issues with multiple statements in `with pytest.raises` blocks. Fixing the test revealed that the later statements were failing. This fixes the check to only descend into `Output` nodes, failing immediately for other nodes. Also, mypy would have caught this, but there was an `ignore` comment on it.

fix check for empty required block

---

CHANGES.rst
src/jinja2/ext.py
tests/test_ext.py

* Refs: https://github.com/python-babel/babel/issues/1049
Checklist:
- Not relevant IMO. 
- Not relevant IMO. 
- There is an unrelated `flake8` failure.

Make nested-trans-block exceptions nicer

---

CHANGES.rst
docs/api.rst
src/jinja2/environment.py

use asyncio.run in Template.render

---

README.md

The README has a `.md` suffix, which tells me it's a Markdown file, yet it uses a reStructuredText code block. This doesn't render as a code block on GitHub, or on [PyPI](https://pypi.org/project/Jinja2/3.1.4/).

Convert rST code block to Markdown in README

---

docs/api.rst

The `nl2br` filter example in the documentation does not work as is, and I needed to make some changes to make it work.
This PR fixes the previously reported https://github.com/pallets/jinja/issues/1769 issue and supersedes the proposed fix (https://github.com/pallets/jinja/pull/1770) as it also fixes the typo in the closing `</p>` tag.
fixes #1769

Fix nl2br example in documentation

---

src/jinja2/runtime.py

Clarifies what operations the default `Undefined` supports. Before this change, the only indication that boolean expressions were supported was one of the examples.

Clarify what operations the default "Undefined" supports

---

docs/templates.rst

Fix error in documentation about whitespace control. 
No issue has been created for this PR (I wasn't sure if I needed to create one for just a doc fix). 
Also I'm not sure where this PR should be merged (main or 3.1.x).

Docs: Fix small error about whitespace control

---

docs/api.rst

Hi everyone!
I was studying Jinja and Flask with @JefersonViana , and noticed a typo in the docs about custom filters.
I hope there is no need for creating an issue for this.
Let me know if you think that there is a better solution.

Fix typo on filter name

---

docs/templates.rst

The doc states that these "return true" but more precisely they're the "typical" short-circuiting boolean operations with Python-like semantics. ``and`` and ``or`` may not return booleans at all depending on their inputs.
---
I had a coworker express the expectation that ``x or y`` in a Jinja template would return a bool, in a context in which ``x`` and ``y`` are both ``str | None``, based on this section of the docs.
I don't read the doc in this way, but strictly speaking that's what it says (these don't say that they're Python-like boolean operations -- they say they "return true").
I think the clarification is possibly helpful and at worst harmless. It was written based off of the Python documentation for the boolean operators.[^1]
[^1]: …

Slightly improve clarity of logical bool ops

---

CHANGES.rst
docs/templates.rst
docs/tricks.rst
src/jinja2/loaders.py

"by default" is a more common wording than "per default". Also clarify what "outer scope" means.
fixes #2058

clarify blocks docs

---

CHANGES.rst
src/jinja2/runtime.py
tests/test_nativetypes.py

Use correct concat function for blocks evaluation

---

CHANGES.rst
src/jinja2/filters.py
tests/test_async_filters.py

unique() filter doesn't work chained after a filter that return an async generator.
This introduces a async variant of the filter transform the async
generator into a list to be able to apply the unique filter.
Fixes #1781
Checklist:

make unique filter async aware

---

CHANGES.rst
src/jinja2/compiler.py
tests/test_compile.py

Makes compiled output deterministic, when doing tuple unpacking to set multiple vars in a single `{% set ... %}` call.
fixes #2021

Make compiled output deterministic for tuple unpacking in set tag

---

CHANGES.rst
src/jinja2/runtime.py
tests/test_api.py
tests/test_runtime.py

Restores erroneous deletions of `__slots__` metadata from `Undefined` types that breaks various serialization/copy mechanisms on Python >= 3.6. Also:
* fix ChainedUndefined to raise AttributeError on unimplemented dunder methods to prevent breaking core Python protocols (including copy)
* add tests
fixes #2025

Preserve `__slots__` metadata on Undefined types

---

CHANGES.rst
src/jinja2/utils.py
tests/test_utils.py

Fix pickle/copy support for the `missing` singleton:
* Fix pickle support for the `missing` singleton.
* Add unit test for pickling the `missing` singleton.
* Add unit test for copying the `missing` singleton.
Fixes #2027

Fix pickle/copy support for the `missing` singleton

---

CHANGES.rst
src/jinja2/sandbox.py
tests/test_security.py

This PR adds the attributes `clear` and `pop` on `MutableSequence` to the default `modifies_known_mutable` check used by `ImmutableSandboxedEnvironment`.
fixes #2032
Let me know if I should add an entry to CHANGES.rst. I didn't see any previous mention of `ImmutableSandboxedEnvironment` in there so I wasn't sure if I should.

sandbox disallows `clear` and `pop` on mutable sequence

---

CHANGES.rst
src/jinja2/compiler.py
tests/test_compile.py

I've fixed a bug that caused an f-string syntax error in the template compilation when a template, that imports a macro, contains curly braces in its name. The bug was caused by the code-generation of an f-string in which the template name is inserted, and when the template name contains curly braces and the generated code gets executed, Python treats the curly braces as f-string braces. I've changed the code-generation to construct the string differently, such that the affected substring is not an f-string. Instead, the different substrings are concatenated using the `+` operator.
- fixes #1792
Checklist:

fix f-string syntax error in code generation

---

CHANGES.rst
src/jinja2/environment.py
tests/test_api.py

Got a wrong behaviour with `Environment.overlay` and seems to me an obvious error code.

fix default for `Environment.overlay(enable_async)`

---

CHANGES.rst
src/jinja2/loaders.py
tests/test_loader.py

`FileSystemLoader` include paths in error

---

CHANGES.rst
src/jinja2/loaders.py
tests/test_loader.py

Explain why the `PackageLoader` failed when the `package_path` directory is missing.
- fixes #1705
Checklist:

Improve the PackageLoader error message

---

CHANGES.rst
src/jinja2/compiler.py
src/jinja2/environment.py
src/jinja2/ext.py
src/jinja2/idtracking.py
src/jinja2/utils.py

These methods always return a new object of the same type as the object they are bound to, even if this is a subclass. Change the annotations to reflect that.
I have not opened an issue, because it's not a functional bug. It just causes issues with static type checkers.
Checklist:

improve annotations for methods returning copies

---

CHANGES.rst
src/jinja2/utils.py
tests/test_utils.py

Don't apply `urlize` to values like `@a@b`.
continues #1870

don't apply `urlize` to `@a@b`

---

CHANGES.rst
src/jinja2/filters.py
tests/test_regression.py

This bugfix allows `pass_context` to be used by tests in combination with `select`, which was previously failing because `select` did not pass the context object, and thus the context would remain `None`. 
Fixes #1624.
Regarding the request for updating `CHANGES.rst`: should I add a new version number (i.e. 3.1.3) to the document for this bugfix? I'm assuming that `3.1.x` is the correct target branch for this PR, but I wasn't entirely sure.
Checklist:

Pass context to test when using select

---

docs/templates.rst

Triple quotes in docs

---

CHANGES.rst
docs/templates.rst
src/jinja2/compiler.py
src/jinja2/parser.py
tests/test_core_tags.py

This fixes a bug that existed because namespaces within `{% set %}` were treated as a special case. This special case had the side-effect of bypassing the code which allows for tuples to be assigned to.
The solution was to make tuple handling (and by extension, primary token handling) aware of namespaces so that namespace tokens can be handled appropriately. This is handled in a backwards-compatible way which ensures that we do not try to parse namespace tokens when we otherwise would be expecting to parse out name tokens with attributes.
Fixes #1413 
Checklist:

Add support for namespaces in tuple parsing

---

CHANGES.rst
src/jinja2/idtracking.py
tests/test_regression.py

This fixes a bug where calling `{% set %}` in all 3 branches of an `{% if %}` block could result in the parameter being undefined sometimes. If the `{% set %}` call was not done in all branches or it was done outside of an `{% if %}` block then the bug would not appear. This was determined to be a bad assumption being made by the ID tracking for variables within the template loader where if the `{% set %}` occurred in all branches then it was not going to be a previously defined variable.
Fixes #1253
Checklist:

Fix bug involving calling set on a template parameter within all branches of an if block

---

CHANGES.rst
pyproject.toml
src/jinja2/__init__.py
uv.lock

As has been done with the other Pallets projects.
The `__version__` attribute is an old pattern from early in Python packaging. Setuptools eventually made it easier to use the pattern by allowing reading the value from the attribute at build time, and some other build backends have done the same.
However, there's no reason to expose this directly in code anymore. It's usually better to use feature detection (`hasattr`, `try/except`) instead. `importlib.metadata.version("jinja2")` can be used to get the version at runtime in a standard way, if it's really needed.

deprecate `__version__`
